### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [tsteinert/tea-cozy#2]
Overall excellent project.

Your css and html is well structured.

I didn't see any major mistakes or errors.

You used descriptive alt text which is great.

To prepare you for the upcoming projects, try using a media query to make this site fit on a mobile device, the final last projects focus on this plus heavy use of flexbox.

https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

https://www.w3schools.com/css/css3_mediaqueries_ex.asp

**Comment by tsteinert** [comment]
Thank you!
